buffers { size_kb: 65536 fill_policy: RING_BUFFER }
duration_ms: 60000
data_sources {
  config {
    name: "linux.ftrace"
    ftrace_config {
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_wakeup"
      atrace_categories: "camera"
      atrace_categories: "gfx"
      atrace_categories: "view"
      atrace_categories: "am"
      atrace_apps: "com.aiphotographer.app"
    }
  }
}
data_sources { config { name: "linux.process_stats" process_stats_config { proc_stats_poll_ms: 1000 } } }
data_sources { config { name: "android.surfaceflinger.frametimeline" } }
